myapp/blog/urls.py
from django.urls import path
from .import views

app_name = "blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("post/<int:post_id>/", views.detail, name="detail"),
    path("new_url/", views.new_url_view, name="new_page_url"),
    path("old_url/", views.old_url_redirect, name="old_url"),
    path("contact/", views.contact, name="contact"),
    path("about/", views.about, name="about"),
    path('search/', views.search, name='search'),
]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("blog.urls")),
]

myapp/blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    img_url = models.ImageField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

#contact model

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)  # optional, tracks when submitted

    def __str__(self):
        return f"{self.name} - {self.email}"

class AboutUs(models.Model):
    content = models.TextField()
    
    

myapp/blog/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label ='Name', max_length=100, required=True)
    email = forms.EmailField(label='Email', required=True)
    message = forms.CharField(label='Message',required=True)

myapp/blog/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.urls import reverse
from .models import Post,AboutUs
from django.http import Http404
from .forms import ContactForm
from .models import Contact
from django.db.models import Q
# Create your views here.
#Static demo data
# posts = [
#         {'id':1,'title':'post 1','content':'content of post 1'},
#         {'id':2,'title':'post 2','content':'content of post 2'},
#         {'id':3,'title':'post 3','content':'content of post 3'},
#         {'id':4,'title':'post 4','content':'content of post 4'},
#         {'id':5,'title':'post 5','content':'content of post 5'},
#         {'id':6,'title':'post 6','content':'content of post 6'},
# ]

def index(request):
    blog_title = "Latest Posts"
    # getting data from post model
    posts = Post.objects.all()
    return render(request,'blog/index.html',{'blog_title':blog_title,'posts':posts})
def detail(request,post_id):
    #static data
    # post = next((item for item in posts if item['id'] == int(post_id)), None)
    # getting data from model by post id
    try:
        post = Post.objects.get(pk=post_id)
    except Post.DoesNotExist:
        raise Http404("post does not exist")
    return render(request,'blog/detail.html',{'post':post})
def old_url_redirect(request):
    return redirect(reverse("blog:new_page_url"))
def new_url_view(request):
    return HttpResponse("this is the new url")

def contact(request):
    form = ContactForm(request.POST)
    if form.is_valid():
       # Manually save to DB
        Contact.objects.create(
          name=form.cleaned_data['name'],
          email=form.cleaned_data['email'],
          message=form.cleaned_data['message']
        )
        success_message = 'Your message has been saved in the database!'
        return render(request, 'blog/contact.html',{
           'form': ContactForm(),  # reset form
           'success_message': success_message
        })

    else:
        form = ContactForm()
    return render(request, 'blog/contact.html', {'form': form})
def about(request):
    about_content = AboutUs.objects.first()
    if about_content is None or not about_content.content:
        about_content = "Default content goes here."
    else:
        about_content = about_content.content

    return render(request,'blog/about.html',{'about_content':about_content})

def post_detail(request, id):
    post = get_object_or_404(Post, id=id)
    related_posts = Post.objects.exclude(id=id)[:3]

    return render(request, 'blog/detail.html', {
        'post': post,
        'related_posts': related_posts
    })

def search(request):
    query = request.GET.get('q')   # input name="q"
    results = []

    if query:
        results = Post.objects.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query)
        )

    return render(request, 'blog/search_results.html', {
        'query': query,
        'results': results
    })

myapp/blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container-fluid ">
    <h3>About Us</h3>
    <div class="d-flex gap-3 justify-content-center mt-5">
        <img src="https://picsum.photos/400/400" alt="">
        <div class="content">
            {{about_content}}
        </div>

    </div>
</div>
{% endblock %}

myapp/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{blog_title | default:"Document"}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body class="min-vh-100 d-flex flex-column">
    <!--header-->
    {% include 'blog/includes/header.html' %}
    <!--dynamic content-->
    <main class="flex-grow-1">
    {% block content %}
    {% endblock %}
</main>
    <!-- footer -->
    {% include 'blog/includes/footer.html' %}
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
   
</body>
</html>

myapp/blog/templates/blog/contact.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="d-flex justify-content-center mt-5">
        <div class="d-flex gap-3 flex-column">
            <h3>Contact Form</h3>
            <!-- Error messages -->
            {% for field in form %}
                {% if field.errors %}
                    <div class="col-12">
                        <span class="fw-bold"> {{field.label_tag}} </span>
                        {% for error in field.errors %}
                        <span class="text-danger"> {{error}} </span>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endfor %}

            <!-- Succes message -->
            {% if success_message %}
                    <div class="alert alert-success" role="alert">
                        {{success_message}}
                    </div>
            {% endif %}

            <form method="post" class="row g-3">
                {% csrf_token %}
                <div class="col-md-6">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" class="form-control" id="name" vlaue="{{name}}" name="name">
                </div>
                <div class="col-md-6">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control" id="email" value="{{email}}" name="email">
                </div>
                <div class="col-12">
                    <label for="message" class="form-label">Message</label>
                    <textarea class="form-control" id="message" name="message" value="{{message}}" rows="4" ></textarea>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>

            </form>
        </div>
    </div>

</div>
{% endblock %}

            

myapp/blog/templates/blog/detail.html
{% extends "blog/base.html" %}
{% block content%} 
    <div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">{{post.title}}</h1>
              <p class="text-muted">{{post.created_at |date:"F j,y"}}</p>
              <img src="{{post.img_url}}" class="img-fluid mb-4" alt="Blog Image">
              <p>{{post.content}}</p>
            </div>
        </div>
    </div>
{% endblock %}

myapp/blog/templates/blog/includes/footer.html
<footer class="bg-dark text-light p-3">
        <div class="d-flex justify-content-center align-items-center text-align-center">
          <span class="text-light">© 2021 Company, Inc</span>
        </div>
</footer>

myapp/blog/templates/blog/includes/header.html
 <header class="p-3 bg-dark text-white">
        <div class="row">
            <div class="col">
                <h3>Blog</h3>
            </div>
            <div class="col">
                <div class="d-flex justify-content-center gap-3">
                    <a class="text-light text-decoration-none" href="/">Home</a>
                    <a class="text-light text-decoration-none" href="/about">About</a>
                    <a class="text-light text-decoration-none" href="/contact">Contact</a>
                </div>
            </div>
        </div>
    </header>

myapp/blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% block content%} 
    <div class="container-fluid ">
        <div class="row my-2">
            <div class="col">
                <h2>{{blog_title}}</h2> <!--upper length truncatewords-->
            </div>
            <form action="{% url 'blog:search' %}" method="get">
  <div class="input-group">
    <input type="text" name="q" class="form-control" placeholder="Search..." required>
    <button class="btn btn-primary" type="submit">
      <i class="bi bi-search"></i>
    </button>
  </div>
</form>

        </div>
        <div class="row m-3">
            {% if posts %}
            {% for post in posts %}
            <div class="col-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <img style="height:300", "width:300" src="{{post.img_url}}" class="img-fluid" alt="...">
                            </div>
                            <div class="col-md-8">
                                <h5 class="card-title">{{post.title}}</h5>
                                <p class="card-text">{{post.content |truncatechars:50}}</p>
                                <div class="d-flex justify-content-between">
                                     <a href="{% url 'blog:detail' post_id=post.id %}">Read More</a>
                                    <a class="text-decoration-none text-dark fw-bold" href="#">Sports</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
                <p> No Posts Available </p>
            {% endif %}
            <div class="col-12 my-3">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="First">
                                <span aria-hidden="true">&laquo; first</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                        <li class="page-item"><span class="page-link">Page 3 of 20.</span></li>
                        <li class="page-item">
                            <a class="page-link" href="?page=4" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page=20" aria-label="Last">
                                <span aria-hidden="true">last &raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                
            </div>
        </div>
        <div class="row">
           
        </div>
        
    </div>
{% endblock %}

myapp/blog/templates/blog/search_results.html
{% extends "blog/base.html" %}
{% block content %}

<div class="container mt-4">
  <h3>
    Search results for: <strong>"{{ query }}"</strong>
  </h3>

  {% if results %}
    <ul class="list-group mt-3">
      {% for post in results %}
        <li class="list-group-item">
          <h5>{{ post.title }}</h5>
          <p>{{ post.content|truncatewords:25 }}</p>
          <a href="{% url 'post_detail' post.id %}">
            Read more →
          </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p class="text-muted mt-3 d-flex align-items-center gap-2">
  <i class="bi bi-search"></i>
  No results found
</p>

  {% endif %}
</div>

{% endblock %}